version: '3'

services:
  # Сервис для конвертации изображений в stage окружении
  avif-converter-stage:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Монтирование папки stage/articles для доступа к изображениям
      - ../stage/articles:/app/stage/articles
    # Команда запуска с указанием окружения
    command: /app/convert_to_avif.sh --environment stage

  # Сервис для конвертации изображений в production окружении
  avif-converter-production:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Монтирование папки production/articles для доступа к изображениям
      - ../production/articles:/app/production/articles
    # Команда запуска с указанием окружения
    command: /app/convert_to_avif.sh --environment production
